### ISSUE TITLE
Intro Height

### ISSUE THREAD

**Issue by spacecheese** [SitehubJS/SitehubJS.github.io#1]
On small viewports the intro div appears squashed. The features divs also fail to correctly align.

**Comment by AgentBlackout** [comment]
What's the point of posting an issue when you're in charge of fixing most issues?

**Comment by spacecheese** [comment]
@AgentBlackout Correction- I fix all issues on this repo.
In reply to the question it's so I remember to fix it on a more capable device

**Comment by AgentBlackout** [comment]
@spacecheese you think i care?
